### ISSUE TITLE
Usage example/documentation

### ISSUE THREAD

**Issue by Danielv123** [carrotsearch/gatsby-transformer-html#8]
I am in need of a transformer to go from a file node to HTML. The source files are HTML, and this project sounds like they would do what I need with some nice extras. But there isn't a single example, which makes it hard to pick up.

**Comment by stanislawosinski** [comment]
Have a look here: https://github.com/carrotsearch/gatsby-starter-apidocs.

**Comment by Danielv123** [comment]
That only explains the APIdocs project - I am using this for a different project because no good plaintext transformer exists for gatsby. As a reference for anybody else coming across this, I did the following:

```
// gatsby-node.js
const { createFilePath } = require(`gatsby-source-filesystem`);
exports.onCreateNode = ({ node, getNode, actions }, { basePath }) => {
  const { createNodeField } = actions;
  if (node.internal.type === `Html`) {
    const slug = createFilePath({ node, getNode, basePath });
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    });
  }
};
```

```
// gatsby-config.js

  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/Bemanning/`,
      },
    },
    `@carrotsearch/gatsby-transformer-html`,
    ......
```

My query:
```
export const query = graphql`
{
    allHtml {
        edges {
        node {
            fields {
            slug
            }
            rawHtml
        }
        }
    }
    }
`
```

Response:
```
{
  "data": {
    "allHtml": {
      "edges": [
        {
          "node": {
            "fields": {
              "slug": "/Bemanning uker lik/Fredag/"
            },
            "rawHtml": "<html xmlns:o=\"urn:schemas-microsoft-com:office:office\"\r\nxmlns:x=\"urn:schemas-microsoft-com:office:excel\"\r\nxmlns=\"http://www.w3.org/TR/REC-html40\">\r\n\r\n<head>
................
```

**Comment by Danielv123** [comment]
I have come upon another issue - it seems the html gets cached, but I can't find any documentation on that, neither here nor in gatsby-source-filesystem. Do you know where that could be, and how it could be disabled?

**Comment by stanislawosinski** [comment]
I'm a Gatsby beginner, to be honest. I've been using the HTML transformer plugin in the live reload development mode and haven't seen any caching issues.

**Comment by stanislawosinski** [comment]
Closing for now, feel free to reopen if needed.
